### PR TITLE
Update zh_CN.lang

### PR DESCRIPTION
**Pull request by bakaxyf**
51ca6b5168d550e28a1b93aeab32862d2ae696fa a39e13768aa4071a02557f618e095e2ebdfbfd8b 8273c6761300d27ada40e63abe552609fcb4510a 9fb563bf34900c30f3d6585bbce1115960d185c0 45572136f302692e365a41a10b3352a5963826ba 4050caadb66939a5b9fb5f7b6ae4c76444c9b92c e1235293ca27cbe7d3b1731158a045a7dc776011 90c62f5ad056da6e03a0338e89a3ac08b6ab3a21 1d4d43989af5800c857f3a2c552259758881a00e 7483001b48de993dc12cd2faa03868f391f0de16 b045538f28035f5dd4293799d067763bad731b8d 7bed2dbff282b081dba1ab4ff02af02a0b23bb3c 7a580eee43789650bbaac6abbb96ef213b1a6bb2 0a6d949649bc4d90af4d1ddbdac983cacb121a26 b483f79538961b2e8234380e17eaa617f15640ce a16f39496124d4b1535660591e15feed01f889ea 98d07a313a4260a621146de50b5edb112174537f e67e8b7a5c6d85ac8d91902d983e031126260ae1 7ea1aa0d99b1c59474a9e1e1ad1d0a069466ce26 62e6572ee50f3270ec78159df889926b4139369b 4578578d0e9adfd8db97ea126e25b7b459bcbd08 3160c349407cf9c814419ed9ae7ecaa441946585 4c812e1932dda39912a87c59a9ba622afed0bbfa edab1c3a7b862dbc44d8886e614fabb49c9907e1

### CODE REVIEW

**Comment by K-4U** [comment]
I would actually prefer it if the localisations would be translated. Can you do that too?

**Comment by bakaxyf** [comment]
OK

**Comment by bakaxyf** [comment]
Missing translation
image

**Comment by bakaxyf** [comment]
Need help.
`tile.fluidPipe.name=Fluid Pipe` `tile.fluidInterface.name=Fluid Interface`
I cant figure out where are them in game .

**Comment by bakaxyf** [comment]
I give the Chinese translation work to @claybiockiller now.

**Comment by claybiockiller** [comment]
I was preparing exam at That time. It's time to transfer now.
当时我正在备考。现在可以转交了。
Claybiockiller(Github)/Clayblockiller(MCF)/Clayblock(MCBBS)

**Comment by K-4U** [comment]
Thank you for this. I'll look into porting it to the 1.8.9, but if i fail, can i contact you again?

**Pull request merged**
